#pragma once

#include <SFML/Window/Keyboard.hpp>
#include <SFML/Window/Mouse.hpp>

#include "sdk/enums.hpp"

// clang-format off
EnumBegin(sf::Keyboard::Key)
    EnumCustomEntry(Unknown, "Unknown")
    EnumCustomEntry(A, "A")
    EnumCustomEntry(B, "B")
    EnumCustomEntry(C, "C")
    EnumCustomEntry(D, "D")
    EnumCustomEntry(E, "E")
    EnumCustomEntry(F, "F")
    EnumCustomEntry(G, "G")
    EnumCustomEntry(H, "H")
    EnumCustomEntry(I, "I")
    EnumCustomEntry(J, "J")
    EnumCustomEntry(K, "K")
    EnumCustomEntry(L, "L")
    EnumCustomEntry(M, "M")
    EnumCustomEntry(N, "N")
    EnumCustomEntry(O, "O")
    EnumCustomEntry(P, "P")
    EnumCustomEntry(Q, "Q")
    EnumCustomEntry(R, "R")
    EnumCustomEntry(S, "S")
    EnumCustomEntry(T, "T")
    EnumCustomEntry(U, "U")
    EnumCustomEntry(V, "V")
    EnumCustomEntry(W, "W")
    EnumCustomEntry(X, "X")
    EnumCustomEntry(Y, "Y")
    EnumCustomEntry(Z, "Z")
    EnumCustomEntry(Num0, "Num0")
    EnumCustomEntry(Num1, "Num1")
    EnumCustomEntry(Num2, "Num2")
    EnumCustomEntry(Num3, "Num3")
    EnumCustomEntry(Num4, "Num4")
    EnumCustomEntry(Num5, "Num5")
    EnumCustomEntry(Num6, "Num6")
    EnumCustomEntry(Num7, "Num7")
    EnumCustomEntry(Num8, "Num8")
    EnumCustomEntry(Num9, "Num9")
    EnumCustomEntry(Escape, "Escape")
    EnumCustomEntry(LControl, "LControl")
    EnumCustomEntry(LShift, "LShift")
    EnumCustomEntry(LAlt, "LAlt")
    EnumCustomEntry(LSystem, "LSystem")
    EnumCustomEntry(RControl, "RControl")
    EnumCustomEntry(RShift, "RShift")
    EnumCustomEntry(RAlt, "RAlt")
    EnumCustomEntry(RSystem, "RSystem")
    EnumCustomEntry(Menu, "Menu")
    EnumCustomEntry(LBracket, "LBracket")
    EnumCustomEntry(RBracket, "RBracket")
    EnumCustomEntry(Semicolon, "Semicolon")
    EnumCustomEntry(Comma, "Comma")
    EnumCustomEntry(Period, "Period")
    EnumCustomEntry(Quote, "Quote")
    EnumCustomEntry(Slash, "Slash")
    EnumCustomEntry(Backslash, "Backslash")
    EnumCustomEntry(Tilde, "Tilde")
    EnumCustomEntry(Equal, "Equal")
    EnumCustomEntry(Hyphen, "Hyphen")
    EnumCustomEntry(Space, "Space")
    EnumCustomEntry(Enter, "Enter")
    EnumCustomEntry(Backspace, "Backspace")
    EnumCustomEntry(Tab, "Tab")
    EnumCustomEntry(PageUp, "PageUp")
    EnumCustomEntry(PageDown, "PageDown")
    EnumCustomEntry(End, "End")
    EnumCustomEntry(Home, "Home")
    EnumCustomEntry(Insert, "Insert")
    EnumCustomEntry(Delete, "Delete")
    EnumCustomEntry(Add, "Add")
    EnumCustomEntry(Subtract, "Subtract")
    EnumCustomEntry(Multiply, "Multiply")
    EnumCustomEntry(Divide, "Divide")
    EnumCustomEntry(Left, "Left")
    EnumCustomEntry(Right, "Right")
    EnumCustomEntry(Up, "Up")
    EnumCustomEntry(Down, "Down")
    EnumCustomEntry(Numpad0, "Numpad0")
    EnumCustomEntry(Numpad1, "Numpad1")
    EnumCustomEntry(Numpad2, "Numpad2")
    EnumCustomEntry(Numpad3, "Numpad3")
    EnumCustomEntry(Numpad4, "Numpad4")
    EnumCustomEntry(Numpad5, "Numpad5")
    EnumCustomEntry(Numpad6, "Numpad6")
    EnumCustomEntry(Numpad7, "Numpad7")
    EnumCustomEntry(Numpad8, "Numpad8")
    EnumCustomEntry(Numpad9, "Numpad9")
    EnumCustomEntry(F1, "F1")
    EnumCustomEntry(F2, "F2")
    EnumCustomEntry(F3, "F3")
    EnumCustomEntry(F4, "F4")
    EnumCustomEntry(F5, "F5")
    EnumCustomEntry(F6, "F6")
    EnumCustomEntry(F7, "F7")
    EnumCustomEntry(F8, "F8")
    EnumCustomEntry(F9, "F9")
    EnumCustomEntry(F10, "F10")
    EnumCustomEntry(F11, "F11")
    EnumCustomEntry(F12, "F12")
    EnumCustomEntry(F13, "F13")
    EnumCustomEntry(F14, "F14")
    EnumCustomEntry(F15, "F15")
    EnumCustomEntry(Pause, "Pause")
    EnumCustomEntry(KeyCount, "KeyCount")
EnumEnd();


EnumBegin(sf::Mouse::Button)
    EnumCustomEntry(Left, "Left")
    EnumCustomEntry(Right, "Right")
    EnumCustomEntry(Middle, "Middle")
    EnumCustomEntry(XButton1, "XButton1")
    EnumCustomEntry(XButton2, "XButton2")
    EnumCustomEntry(ButtonCount, "ButtonCount")
EnumEnd();

// clang-format on
